### ISSUE TITLE
GS compatibility package seem to remove text cursor

### ISSUE THREAD

**Issue by hogoww** [ba-st/Buoy#95]
Hello,

[Pharo 12]

While trying to install Stargate on Pharo 12, I noticed I was loosing my text cursor.  
After a *long* debug I finally got it down to Buoy, and more precisely something inside baselineGS64Development.  
I also needed to disable baselineChronology (which I'm less happy about, as it feels it's probably useful for Pharo too..).  
I don't know whether I'll continue to debug this.

To reproduce, just try to install Stargate and/or Buoy on its own.
(Buoy on its own crashes when installing the baseline, and loading GS64-extensions).

To test whether the bug is present:
Open a workspace/playground (the text cursor should be displayed in the initial state)

Shouldn't the packages GS64 be only loaded in a GS environment? 

Pierre

**Comment by gcotelli** [comment]
These packages aren't intended to be loaded in Pharo. What baseline group are you loading?

**Comment by hogoww** [comment]
Simply right click and install baseline of Buoy (Default).
So I'm assuming "Default" (?)

**Comment by gcotelli** [comment]
Probably we aren't setting anything as default so it is loading anything that Metacello does when not configured. Can you try loading the `Development` group or any other that suites your situation as described in the [docs](https://github.com/ba-st/Buoy/blob/release-candidate/docs/reference/Baseline-groups.md). I will update the baseline to load it by default.

**Comment by gcotelli** [comment]
And BTW, probably the same is happening with Stargate. I'm pretty sure that if you load one of the groups declared in the Baseline and not default It will work. Are you following the [loading instructions ](https://github.com/ba-st/Stargate/blob/release-candidate/docs/how-to/how-to-load-in-pharo.md) ?

**Comment by hogoww** [comment]
Indeed.
My appologies, I'm just used to load default without thinking.

**Comment by gcotelli** [comment]
I will update anyway the default group so it's less confusing when using the default loading option. Opened #96 to not forget.
